In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({
    "Patient_ID": [101, 102, 103, 104, 105, 106, 107],
    "Age": [25, 30, 28, np.nan, 45, 50, 29],
    "Weight": [58, 75, np.nan, 55, 85, 90, np.nan],
    "BloodPressure": [120, np.nan, 130, 110, 140, 150, np.nan],
    "Cholesterol": [200, 210, 220, 190, np.nan, 250, 230],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Male", "Female"]
})

In [5]:
df.head()

   Patient_ID   Age  Weight  BloodPressure  Cholesterol  Gender
0         101  25.0    58.0          120.0        200.0    Male
1         102  30.0    75.0            NaN        210.0  Female
2         103  28.0     NaN          130.0        220.0    Male
3         104   NaN    55.0          110.0        190.0  Female
4         105  45.0    85.0          140.0          NaN    Male

In [6]:
df.isnull().sum()

Patient_ID       0
Age              1
Weight           2
BloodPressure    2
Cholesterol      1
Gender           0
dtype: int64

In [8]:
df_drop = df.dropna()
df_drop

   Patient_ID   Age  Weight  BloodPressure  Cholesterol Gender
0         101  25.0    58.0          120.0        200.0   Male
5         106  50.0    90.0          150.0        250.0   Male

In [9]:
df_drop.to_csv("health_Monitering.csv")

In [11]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19224\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [13]:
df['BloodPressure'].fillna(df['BloodPressure'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19224\1182849210.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BloodPressure'].fillna(df['BloodPressure'].mean(),inplace=True)

In [13]:
df['BloodPressure'].fillna(df['BloodPressure'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19224\1182849210.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['BloodPressure'].fillna(df['BloodPressure'].mean(),inplace=True)

In [12]:
df['Weight'].fillna(df['Weight'].median(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19224\3785350539.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Weight'].fillna(df['Weight'].median(),inplace=True)

In [15]:
df['Cholesterol'].fillna(df['Cholesterol'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19224\3040995220.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Cholesterol'].fillna(df['Cholesterol'].mean(),inplace=True)

In [16]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,StandardScaler

In [18]:
le = LabelEncoder()
df['le_Gender'] = le.fit_transform(df['Gender'])

In [19]:
df

   Patient_ID   Age  Weight  BloodPressure  Cholesterol  Gender  le_Gender
0         101  25.0    58.0          120.0   200.000000    Male          1
1         102  30.0    75.0          130.0   210.000000  Female          0
2         103  28.0    75.0          130.0   220.000000    Male          1
3         104  34.5    55.0          110.0   190.000000  Female          0
4         105  45.0    85.0          140.0   216.666667    Male          1
5         106  50.0    90.0          150.0   250.000000    Male          1
6         107  29.0    75.0          130.0   230.000000  Female          0

In [20]:
mm = MinMaxScaler()
std = StandardScaler()

In [21]:
df[['mm_Age','mm_Weight']] = mm.fit_transform(df[['Age','Weight']])

In [22]:
df[['std_Cholesterol']] = std.fit_transform(df[['Cholesterol']])

In [23]:
df

,Patient_ID,Age,Weight,BloodPressure,Cholesterol,Gender,le_Gender,mm_Age,mm_Weight,std_Cholesterol
0,101,25.0,58.0,120.0,200.000000,Male,1,0.00,0.085714,-9.128709e-01
1,102,30.0,75.0,130.0,210.000000,Female,0,0.20,0.571429,-3.651484e-01
2,103,28.0,75.0,130.0,220.000000,Male,1,0.12,0.571429,1.825742e-01
3,104,34.5,55.0,110.0,190.000000,Female,0,0.38,0.000000,-1.460593e+00
4,105,45.0,85.0,140.0,216.666667,Male,1,0.80,0.857143,-1.556721e-15
5,106,50.0,90.0,150.0,250.000000,Male,1,1.00,1.000000,1.825742e+00
6,107,29.0,75.0,130.0,230.000000,Female,0,0.16,0.571429,7.302967e-01