In [2]:
import pandas as pd
import numpy as np

In [41]:
# age = mean , height = median , city = mode , 
df = pd.DataFrame({"age":[27,28,29,'None',30,31,'None',32,33,40],
                  "height":[160,161,162,'None',163,164,165,'None',166,170],
                  "wt":[54,56,58,59,'None',60,61,'None',62,63],
                  "City":['kolkata','up','kolkata','bihar','np.na','np.na','up','kanpur','Mathura','np.na'],
                  "marks":[80,90,88,86,'None',88,92,93,'None',94]})

In [42]:
df.replace(["None", "np.na"], np.nan, inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24260\1942387647.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(["None", "np.na"], np.nan, inplace=True)

In [43]:
df.to_csv('Sample.csv',index=False)

In [44]:
df.head()

    age  height    wt     City  marks
0  27.0   160.0  54.0  kolkata   80.0
1  28.0   161.0  56.0       up   90.0
2  29.0   162.0  58.0  kolkata   88.0
3   NaN     NaN  59.0    bihar   86.0
4  30.0   163.0   NaN      NaN    NaN

In [45]:
df.isnull().sum()

age       2
height    2
wt        2
City      3
marks     2
dtype: int64

In [46]:
df_drop = df.dropna()
df_drop

    age  height    wt     City  marks
0  27.0   160.0  54.0  kolkata   80.0
1  28.0   161.0  56.0       up   90.0
2  29.0   162.0  58.0  kolkata   88.0

In [47]:
df_drop.to_csv('SampleData.csv' ,index=False)

In [48]:
df_drop.isnull().sum()

age       0
height    0
wt        0
City      0
marks     0
dtype: int64

In [49]:
df['age'].fillna(df['age'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24260\1492264711.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean(),inplace=True)

In [50]:
df['height'].fillna(df['height'].median(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24260\4270375056.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['height'].fillna(df['height'].median(),inplace=True)

In [51]:
df['wt'].fillna(method='ffill', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24260\1803913944.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['wt'].fillna(method='ffill', inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_24260\1803913944.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['wt'].fillna(method='ffill', inplace=True)

In [52]:
df['City'].fillna(df['City'].mode()[0],inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24260\689064380.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['City'].fillna(df['City'].mode()[0],inplace=True)

In [53]:
df['marks'].fillna(method='bfill', inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_24260\4189831192.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['marks'].fillna(method='bfill', inplace=True)
C:\Users\HP\AppData\Local\Temp\ipykernel_24260\4189831192.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['marks'].fillna(method='bfill', inplace=True)

In [55]:
df

     age  height    wt     City  marks
0  27.00   160.0  54.0  kolkata   80.0
1  28.00   161.0  56.0       up   90.0
2  29.00   162.0  58.0  kolkata   88.0
3  31.25   163.5  59.0    bihar   86.0
4  30.00   163.0  59.0  kolkata   88.0
5  31.00   164.0  60.0  kolkata   88.0
6  31.25   165.0  61.0       up   92.0
7  32.00   163.5  61.0   kanpur   93.0
8  33.00   166.0  62.0  Mathura   94.0
9  40.00   170.0  63.0  kolkata   94.0

In [62]:
from sklearn.preprocessing import MinMaxScaler,StandardScaler,LabelEncoder,OneHotEncoder

In [57]:
mm = MinMaxScaler()
std = StandardScaler()

In [58]:
df[['mm_age','mm_height']] = mm.fit_transform(df[['age','height']])

In [60]:
df[['std_wt']] = std.fit_transform(df[['wt']])

In [61]:
df

     age  height    wt     City  marks    mm_age  mm_height    std_wt
0  27.00   160.0  54.0  kolkata   80.0  0.000000       0.00 -2.030964
1  28.00   161.0  56.0       up   90.0  0.076923       0.10 -1.264563
2  29.00   162.0  58.0  kolkata   88.0  0.153846       0.20 -0.498161
3  31.25   163.5  59.0    bihar   86.0  0.326923       0.35 -0.114960
4  30.00   163.0  59.0  kolkata   88.0  0.230769       0.30 -0.114960
5  31.00   164.0  60.0  kolkata   88.0  0.307692       0.40  0.268241
6  31.25   165.0  61.0       up   92.0  0.326923       0.50  0.651441
7  32.00   163.5  61.0   kanpur   93.0  0.384615       0.35  0.651441
8  33.00   166.0  62.0  Mathura   94.0  0.461538       0.60  1.034642
9  40.00   170.0  63.0  kolkata   94.0  1.000000       1.00  1.417843

In [70]:
ohe = OneHotEncoder(sparse_output=False)
ohe_array = ohe.fit_transform(df[['City']])
ohe_columns = ohe.get_feature_names_out(['City'])
df_ohe = pd.DataFrame(ohe_array, columns=ohe_columns)

df_ohe

   City_Mathura  City_bihar  City_kanpur  City_kolkata  City_up
0           0.0         0.0          0.0           1.0      0.0
1           0.0         0.0          0.0           0.0      1.0
2           0.0         0.0          0.0           1.0      0.0
3           0.0         1.0          0.0           0.0      0.0
4           0.0         0.0          0.0           1.0      0.0
5           0.0         0.0          0.0           1.0      0.0
6           0.0         0.0          0.0           0.0      1.0
7           0.0         0.0          1.0           0.0      0.0
8           1.0         0.0          0.0           0.0      0.0
9           0.0         0.0          0.0           1.0      0.0

In [71]:
le = LabelEncoder()

In [74]:
df['le_City'] = le.fit_transform(df['City'])

In [73]:
df

     age  height    wt     City  marks    mm_age  mm_height    std_wt  le_City
0  27.00   160.0  54.0  kolkata   80.0  0.000000       0.00 -2.030964        3
1  28.00   161.0  56.0       up   90.0  0.076923       0.10 -1.264563        4
2  29.00   162.0  58.0  kolkata   88.0  0.153846       0.20 -0.498161        3
3  31.25   163.5  59.0    bihar   86.0  0.326923       0.35 -0.114960        1
4  30.00   163.0  59.0  kolkata   88.0  0.230769       0.30 -0.114960        3
5  31.00   164.0  60.0  kolkata   88.0  0.307692       0.40  0.268241        3
6  31.25   165.0  61.0       up   92.0  0.326923       0.50  0.651441        4
7  32.00   163.5  61.0   kanpur   93.0  0.384615       0.35  0.651441        2
8  33.00   166.0  62.0  Mathura   94.0  0.461538       0.60  1.034642        0
9  40.00   170.0  63.0  kolkata   94.0  1.000000       1.00  1.417843        3