In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame({
    "Emp_ID": [201, 202, 203, 204, 205, 206, 207],
    "Age": [23, 29, np.nan, 35, 40, 45, 31],
    "Salary": [25000, 32000, 28000, np.nan, 50000, 60000, 35000],
    "Experience": [1, 3, 2, 5, np.nan, 8, 4],
    "Performance_Score": [3.5, np.nan, 4.0, 4.5, 4.2, np.nan, 3.8],
    "Gender": ["Male", "Female", "Male", "Female", "Male", "Male", "Female"]
})

In [3]:
df.isnull().sum()

Emp_ID               0
Age                  1
Salary               1
Experience           1
Performance_Score    2
Gender               0
dtype: int64

In [4]:
df_drop = df.dropna()

In [5]:
df_drop.to_csv('Employee_Performance.csv')

In [6]:
df['Age'].fillna(df['Age'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19348\694922604.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(),inplace=True)

In [7]:
df['Salary'].fillna(df['Salary'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19348\2738737218.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary'].fillna(df['Salary'].mean(),inplace=True)

In [8]:
df['Experience'].fillna(df['Experience'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19348\445394033.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Experience'].fillna(df['Experience'].mean(),inplace=True)

In [9]:
df['Performance_Score'].fillna(df['Performance_Score'].mean(),inplace=True)

C:\Users\HP\AppData\Local\Temp\ipykernel_19348\1041889571.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Performance_Score'].fillna(df['Performance_Score'].mean(),inplace=True)

In [10]:
from sklearn.preprocessing import LabelEncoder,MinMaxScaler,StandardScaler

In [11]:
le = LabelEncoder()

In [12]:
df['le_Gender'] = le.fit_transform(df['Gender'])

In [13]:
df

,Emp_ID,Age,Salary,Experience,Performance_Score,Gender,le_Gender
0,201,23.000000,25000.000000,1.000000,3.5,Male,1
1,202,29.000000,32000.000000,3.000000,4.0,Female,0
2,203,33.833333,28000.000000,2.000000,4.0,Male,1
3,204,35.000000,38333.333333,5.000000,4.5,Female,0
4,205,40.000000,50000.000000,3.833333,4.2,Male,1
5,206,45.000000,60000.000000,8.000000,4.0,Male,1
6,207,31.000000,35000.000000,4.000000,3.8,Female,0

In [14]:
mm = MinMaxScaler()
std = StandardScaler()

In [15]:
df[['mm_age','mm_salary']] = mm.fit_transform(df[['Age','Salary']])
df[['std_per']] = std.fit_transform(df[['Performance_Score']])

In [16]:
df

,Emp_ID,Age,Salary,Experience,Performance_Score,Gender,le_Gender,mm_age,mm_salary,std_per
0,201,23.000000,25000.000000,1.000000,3.5,Male,1,0.000000,0.000000,-1.737021
1,202,29.000000,32000.000000,3.000000,4.0,Female,0,0.272727,0.200000,0.000000
2,203,33.833333,28000.000000,2.000000,4.0,Male,1,0.492424,0.085714,0.000000
3,204,35.000000,38333.333333,5.000000,4.5,Female,0,0.545455,0.380952,1.737021
4,205,40.000000,50000.000000,3.833333,4.2,Male,1,0.772727,0.714286,0.694808
5,206,45.000000,60000.000000,8.000000,4.0,Male,1,1.000000,1.000000,0.000000
6,207,31.000000,35000.000000,4.000000,3.8,Female,0,0.363636,0.285714,-0.694808