## Imbalanced Dataset Handling

###### 1. Upsampling
###### 2. Down Sampling

In [1]:
import numpy as np 
import pandas as pd

In [2]:
# set the random seed for reproducibility
np.random.seed(123)

# Create a dataframe with two classes
n_sample = 1000
class_0_ratio = 0.9
n_class_0 = int(n_sample * class_0_ratio)
n_class_1 = n_sample - n_class_0

In [3]:
n_class_0,n_class_1

(900, 100)

In [11]:
class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target' : [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_2' : np.random.normal(loc=0,scale=1,size=n_class_1),
    'target' : [1] * n_class_1
})

In [14]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [15]:
df.head()

   feature_1  feature_2  target
0  -1.774224   0.285744       0
1  -1.201377   0.333279       0
2   1.096257   0.531807       0
3   0.861037  -0.354766       0
4  -1.520367  -1.120815       0

In [16]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

## UpSampling

In [17]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [18]:
df_minority.head()

     feature_1  feature_2  target
900  -2.643425   0.571923       1
901  -0.448991  -0.217233       1
902  -0.358907   0.054318       1
903   0.133194   0.155998       1
904  -0.644242   0.467810       1

In [19]:
df_majority.head()

   feature_1  feature_2  target
0  -1.774224   0.285744       0
1  -1.201377   0.333279       0
2   1.096257   0.531807       0
3   0.861037  -0.354766       0
4  -1.520367  -1.120815       0

In [21]:
## up Sampling perform 
from sklearn.utils import resample

In [22]:
df_minority_upsample = resample(df_minority,
                               replace=True,   ## Sample with replacement
                               n_samples=len(df_majority),  ## to match the majority class
                               random_state=42
                               )

In [23]:
df_minority_upsample.shape

(900, 3)

In [26]:
df_minority_upsample['target'].value_counts()

target
1    900
Name: count, dtype: int64

In [27]:
df_upsampled = pd.concat([df_majority,df_minority_upsample])

In [29]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [31]:
class_0 = pd.DataFrame({
    'feature_0' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_0),
    'target' : [0] * n_class_0
})
class_1 = pd.DataFrame({
    'feature_0' : np.random.normal(loc=0,scale=1,size=n_class_1),
    'feature_1' : np.random.normal(loc=0,scale=1,size=n_class_1),
    'target' : [1] * n_class_1
})

In [33]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [37]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [38]:
df_minority = df[df['target'] == 1]
df_majority = df[df['target'] == 0]

In [39]:
df_majority_downsample = resample(df_majority,
                                 replace=True,  ## Sample with replacement
                                 n_samples=len(df_minority),  ## to match the minority class
                                 random_state=42)

In [43]:
df_majority_downsample['target'].value_counts()

target
0    100
Name: count, dtype: int64

In [44]:
df_downsampled = pd.concat([df_majority,df_majority_downsample])

In [45]:
df_downsampled['target'].value_counts()

target
0    1000
Name: count, dtype: int64